//
//  MemoryQuestionRepository.swift
//  MongoDBQuestions
//
//  Created by Stephen Hu on 2024/1/2.
//

import Foundation
class MemoryQuestionRepository:IQuestionRepository
{
    let questions:[Question]
    
    init()
    {
        questions = [
            Question(id: UUID(uuidString: "b98171f3-f4a4-47f9-b43e-15b377ffea97")!, questionDescription: "test question", title: "test 1", options: [QuestionOption(optionValue: "test right", optionId: "1"), QuestionOption(optionValue: "test fail", optionId: "2")], correctOptionIds: ["1"], groups: ["All", "Test"]),
            Question(id: UUID(uuidString: "a3c20c28-5ab9-45a2-81d0-d0779c923b10")!, questionDescription: "test question 2", title: "test 2", options: [QuestionOption(optionValue: "test right 1", optionId: "1"), QuestionOption(optionValue: "test fail", optionId: "2"), QuestionOption(optionValue: "test right 2", optionId: "3")], correctOptionIds: ["1", "3"], groups: ["All", "Test"]),
            Question(id: UUID(uuidString: "72350a8b-470c-4ab9-ad67-da249d66da0a")!, questionDescription: "test question 3", title: "test 3", options: [QuestionOption(optionValue: "test right 1", optionId: "1"), QuestionOption(optionValue: "test fail", optionId: "2"), QuestionOption(optionValue: "test right 2", optionId: "3")], correctOptionIds: ["1", "3"], groups: ["All", "Test"]),
            Question(id: UUID(uuidString: "c4883f75-bd28-451e-aeb4-183c3d9d5094")!, questionDescription: "test question 4", title: "test 4", options: [QuestionOption(optionValue: "test right 1", optionId: "1"), QuestionOption(optionValue: "test fail", optionId: "2"), QuestionOption(optionValue: "test right 2", optionId: "3")], correctOptionIds: ["1", "3"], groups: ["All", "Test"]),
            Question(id: UUID(uuidString: "4be79f3b-0a67-4ece-b8e3-4943a9cf683e")!, questionDescription: "test question 5", title: "test 5", options: [QuestionOption(optionValue: "test right 1", optionId: "1"), QuestionOption(optionValue: "test fail", optionId: "2"), QuestionOption(optionValue: "test right 2", optionId: "3")], correctOptionIds: ["1", "3"], groups: ["All", "Test"]),
            Question(id: UUID(uuidString: "2ea5e096-5cc7-47ad-84e8-a9fc7bde697b")!, questionDescription: "test question 6", title: "test 6", options: [QuestionOption(optionValue: "test right 1", optionId: "1"), QuestionOption(optionValue: "test fail", optionId: "2"), QuestionOption(optionValue: "test right 2", optionId: "3")], correctOptionIds: ["1", "3"], groups: ["All", "Test"]),
            Question(id: UUID(uuidString: "45f20e4b-ab53-4c8e-b687-c960be1f9c86")!, questionDescription: "test question 7", title: "test 7", options: [QuestionOption(optionValue: "test right 1", optionId: "1"), QuestionOption(optionValue: "test fail", optionId: "2"), QuestionOption(optionValue: "test right 2", optionId: "3")], correctOptionIds: ["1", "3"], groups: ["All", "Test"]),
            Question(id: UUID(uuidString: "b98171f3-f4a4-47f9-b43e-15b377ffea97")!, questionDescription: "test question 8", title: "test 8", options: [QuestionOption(optionValue: "test right 1", optionId: "1"), QuestionOption(optionValue: "test fail", optionId: "2"), QuestionOption(optionValue: "test right 2", optionId: "3")], correctOptionIds: ["1", "3"], groups: ["All", "Test"]),
            Question(id: UUID(uuidString: "a3c20c28-5ab9-45a2-81d0-d0779c923b10")!, questionDescription: "test question 9", title: "test 9", options: [QuestionOption(optionValue: "test right 1", optionId: "1"), QuestionOption(optionValue: "test fail", optionId: "2"), QuestionOption(optionValue: "test right 2", optionId: "3")], correctOptionIds: ["1", "3"], groups: ["All", "Test"]),
            Question(id: UUID(uuidString: "c1412d44-990d-417d-9909-f2bb916ea40e")!, questionDescription: "test question 10", title: "test 10", options: [QuestionOption(optionValue: "test right 1", optionId: "1"), QuestionOption(optionValue: "test right 2", optionId: "2"), QuestionOption(optionValue: "test right 3", optionId: "3")], correctOptionIds: ["1", "2", "3"], groups: ["All", "Test"]),
            Question(id: UUID(uuidString: "b02c1767-d08d-484d-973c-194b129d2e11")!, questionDescription: "test question 11", title: "test 11", options: [QuestionOption(optionValue: "test right 1", optionId: "1"), QuestionOption(optionValue: "test right 2", optionId: "2"), QuestionOption(optionValue: "test right 3", optionId: "3")], correctOptionIds: ["1", "2", "3"], groups: ["All", "Test"])，
            Question(id: UUID(uuidString: "b98171f3-f4a4-47f9-b43e-15b377ffea97")!, questionDescription: "test question 12", title: "test 12", options: [QuestionOption(optionValue: "test right 1", optionId: "1"), QuestionOption(optionValue: "test right 2", optionId: "2"), QuestionOption(optionValue: "test right 3", optionId: "3")], correctOptionIds: ["1", "2", "3"], groups: ["All", "Test"]),
            Question(id: UUID(uuidString: "a3c20c28-5ab9-45a2-81d0-d0779c923b10")!, questionDescription: "test question 13", title: "test 13", options: [QuestionOption(optionValue: "test right 1", optionId: "1"), QuestionOption(optionValue: "test right 2", optionId: "2"), QuestionOption(optionValue: "test right 3", optionId: "3")], correctOptionIds: ["1", "2", "3"], groups: ["All", "Test"]),
            Question(id: UUID(uuidString: "72350a8b-470c-4ab9-ad67-da249d66da0a")!, questionDescription: "test question 14", title: "test 14", options: [QuestionOption(optionValue: "test right 1", optionId: "1"), QuestionOption(optionValue: "test right 2", optionId: "2"), QuestionOption(optionValue: "test right 3", optionId: "3")], correctOptionIds: ["1", "2", "3"], groups: ["All", "Test"]),
            Question(id: UUID(uuidString: "c4883f75-bd28-451e-aeb4-183c3d9d5094")!, questionDescription: "test question 15", title: "test 15", options: [QuestionOption(optionValue: "test right 1", optionId: "1"), QuestionOption(optionValue: "test right 2", optionId: "2"), QuestionOption(optionValue: "test right 3", optionId: "3")], correctOptionIds: ["1", "2", "3"], groups: ["All", "Test"]),
            Question(id: UUID(uuidString: "4be79f3b-0a67-4ece-b8e3-4943a9cf683e")!, questionDescription: "test question 16", title: "test 16", options: [QuestionOption(optionValue: "test right 1", optionId: "1"), QuestionOption(optionValue: "test right 2", optionId: "2"), QuestionOption(optionValue: "test right 3", optionId: "3")], correctOptionIds: ["1", "2", "3"], groups: ["All", "Test"]),
            Question(id: UUID(uuidString: "2ea5e096-5cc7-47ad-84e8-a9fc7bde697b")!, questionDescription: "test question 17", title: "test 17", options: [QuestionOption(optionValue: "test right 1", optionId: "1"), QuestionOption(optionValue: "test fail", optionId: "2")], correctOptionIds: ["1"], groups: ["All", "Test"]),
            Question(id: UUID(uuidString: "45f20e4b-ab53-4c8e-b687-c960be1f9c86")!, questionDescription: "test question 18", title: "test 18", options: [QuestionOption(optionValue: "test right 1", optionId: "1"), QuestionOption(optionValue: "test fail", optionId: "2")], correctOptionIds: ["1"], groups: ["All", "Test"]),
            Question(id: UUID(uuidString: "b98171f3-f4a4-47f9-b43e-15b377ffea97")!, questionDescription: "test question 19", title: "test 19", options: [QuestionOption(optionValue: "test right 1", optionId: "1"), QuestionOption(optionValue: "test fail", optionId: "2")], correctOptionIds: ["1"], groups: ["All", "Test"]),
            Question(id: UUID(uuidString: "a3c20c28-5ab9-45a2-81d0-d0779c923b10")!, questionDescription: "test question 20", title: "test 20", options: [QuestionOption(optionValue: "test right 1", optionId: "1"), QuestionOption(optionValue: "test fail", optionId: "2")], correctOptionIds: ["1"], groups: ["All", "Test"]),
            Question(id: UUID(uuidString: "c1412d44-990d-417d-9909-f2bb916ea40e")!, questionDescription: "test question 21", title: "test 21", options: [QuestionOption(optionValue: "test right 1", optionId: "1"), QuestionOption(optionValue: "test fail", optionId: "2")], correctOptionIds: ["1"], groups: ["All", "Test"]),
            Question(id: UUID(uuidString: "b02c1767-d08d-484d-973c-194b129d2e11")!, questionDescription: "test question 22", title: "test 22", options: [QuestionOption(optionValue: "test right 1", optionId: "1"), QuestionOption(optionValue: "test fail", optionId: "2")], correctOptionIds: ["1"], groups: ["All", "Test"]),
            Question(id: UUID(uuidString: "b98171f3-f4a4-47f9-b43e-15b377ffea97")!, questionDescription: "test question 23", title: "test 23", options: [QuestionOption(optionValue: "test right", optionId: "1"), QuestionOption(optionValue: "test fail", optionId: "2")], correctOptionIds: ["1"], groups: ["All", "Test"]),
            Question(id: UUID(uuidString: "a3c20c28-5ab9-45a2-81d0-d0779c923b10")!, questionDescription: "test question 24", title: "test 24", options: [QuestionOption(optionValue: "test right 1", optionId: "1"), QuestionOption(optionValue: "test fail", optionId: "2"), QuestionOption(optionValue: "test right 2", optionId: "3")], correctOptionIds: ["1", "3"], groups: ["All", "Test"]),
            Question(id: UUID(uuidString: "72350a8b-470c-4ab9-ad67-da249d66da0a")!, questionDescription: "test question 25", title: "test 25", options: [QuestionOption(optionValue: "test right 1", optionId: "1"), QuestionOption(optionValue: "test fail", optionId: "2"), QuestionOption(optionValue: "test right 2", optionId: "3")], correctOptionIds: ["1", "3"], groups: ["All", "Test"]),
            Question(id: UUID(uuidString: "c4883f75-bd28-451e-aeb4-183c3d9d5094")!, questionDescription: "test question 26", title: "test 26", options: [QuestionOption(optionValue: "test right 1", optionId: "1"), QuestionOption(optionValue: "test fail", optionId: "2"), QuestionOption(optionValue: "test right 2", optionId: "3")], correctOptionIds: ["1", "3"], groups: ["All", "Test"]),
            Question(id: UUID(uuidString: "4be79f3b-0a67-4ece-b8e3-4943a9cf683e")!, questionDescription: "test question 27", title: "test 27", options: [QuestionOption(optionValue: "test right 1", optionId: "1"), QuestionOption(optionValue: "test fail", optionId: "2"), QuestionOption(optionValue: "test right 2", optionId: "3")], correctOptionIds: ["1", "3"], groups: ["All", "Test"]),
            Question(id: UUID(uuidString: "2ea5e096-5cc7-47ad-84e8-a9fc7bde697b")!, questionDescription: "test question 28", title: "test 28", options: [QuestionOption(optionValue: "test right 1", optionId: "1"), QuestionOption(optionValue: "test fail", optionId: "2")], correctOptionIds: ["1"], groups: ["All", "Test"]),
            Question(id: UUID(uuidString: "45f20e4b-ab53-4c8e-b687-c960be1f9c86")!, questionDescription: "test question 29", title: "test 29", options: [QuestionOption(optionValue: "test right 1", optionId: "1"), QuestionOption(optionValue: "test fail", optionId: "2")], correctOptionIds: ["1"], groups: ["All", "Test"]),
            Question(id: UUID(uuidString: "b98171f3-f4a4-47f9-b43e-15b377ffea97")!, questionDescription: "test question 30", title: "test 30", options: [QuestionOption(optionValue: "test right", optionId: "1"), QuestionOption(optionValue: "test fail", optionId: "2")], correctOptionIds: ["1"], groups: ["All", "Test"]),
            Question(id: UUID(uuidString: "a3c20c28-5ab9-45a2-81d0-d0779c923b10")!, questionDescription: "test question 31", title: "test 31", options: [QuestionOption(optionValue: "test right 1", optionId: "1"), QuestionOption(optionValue: "test right 2", optionId: "2"), QuestionOption(optionValue: "test right 3", optionId: "3")], correctOptionIds: ["1", "2", "3"], groups: ["All", "Test"]),
            Question(id: UUID(uuidString: "c1412d44-990d-417d-9909-f2bb916ea40e")!, questionDescription: "test question 32", title: "test 32", options: [QuestionOption(optionValue: "test right 1", optionId: "1"), QuestionOption(optionValue: "test right 2", optionId: "2"), QuestionOption(optionValue: "test right 3", optionId: "3")], correctOptionIds: ["1", "2", "3"], groups: ["All", "Test"]),
            Question(id: UUID(uuidString: "b02c1767-d08d-484d-973c-194b129d2e11")!, questionDescription: "test question 33", title: "test 33", options: [QuestionOption(optionValue: "test right 1", optionId: "1"), QuestionOption(optionValue: "test right 2", optionId: "2")], correctOptionIds: ["1", "2"], groups: ["All", "Test"]),
            Question(id: UUID(uuidString: "b98171f3-f4a4-47f9-b43e-15b377ffea97")!, questionDescription: "test question 34", title: "test 34", options: [QuestionOption(optionValue: "test right", optionId: "1"), QuestionOption(optionValue: "test fail", optionId: "2")], correctOptionIds: ["1"], groups: ["All", "Test"]),
            Question(id: UUID(uuidString: "a3c20c28-5ab9-45a2-81d0-d0779c923b10")!, questionDescription: "test question 35", title: "test 35", options: [QuestionOption(optionValue: "test right 1", optionId: "1"), QuestionOption(optionValue: "test right 2", optionId: "2")], correctOptionIds: ["1", "2"], groups: ["All", "Test"]),
        ]
    }
    
    func GetAllQuestions(count: Int) -> [Question] {
        return GetQeustionsByGroup(inputGroup:"All", count:count)
    }
    
    func GetQeustionsByGroup(inputGroup: String, count: Int) -> [Question] {
        return Array(questions.filter{question in question.groups.contains(inputGroup)}.shuffled()[0..<count])
    }
}
